### ISSUE TITLE
tests fail on Mac OS X

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#114]
Not clear what or why, but corrrespondences fail on Mac OS X 

`      Start 15: check_correspondences

15: Test command: /Users/alex/Documents/OpenPTV/openptv/liboptv/build/tests/check_correspondences
15: Test timeout computed to be: 9.99988e+06
15: Running suite(s): Testing correspondences
15: Overflow in correspondences.
15: 88%: Checks: 9, Failures: 0, Errors: 1
15: /Users/alex/Documents/OpenPTV/openptv/liboptv/tests/check_correspondences.c:445:E:Calibration target correspondences:test_correspondences:0: (after this point) Received signal 10 (Bus error: 10)
15/15 Test #15: check_correspondences ............***Failed    0.05 sec

93% tests passed, 1 tests failed out of 15

Total Test time (real) =   0.66 sec
`

**Comment by alexlib** [comment]
I do not know why it happens on Mac and does not happen on Ubuntu (tested it on a virtual box), my branch with additional prints is

https://github.com/alexlib/openptv/tree/failing_correspondences

**Comment by yosefm** [comment]
Please try on both with cmake -DCMAKE_BUILD_TYPE=Debug 
and then with -DCMAKE_BUILD_TYPE=Release

If there is a difference in any of them, then it's a memory corruption thing. this is a good way to eliminate that option without a debugger.

**Comment by alexlib** [comment]
both fail. 
tried after `-DCMAKE_BUILD_TYPE=Debug` also:
`ctest -VV -lefence` 
but it does not show a thing (probably I use it wrong)

**Comment by yosefm** [comment]
Is this still happening?

**Comment by alexlib** [comment]
yes, sometimes, not always the last test (in the present master) fails on correspondences
sometimes it passes

**Comment by yosefm** [comment]
Ok, it would take me some serious effort to get and install an OSX virtual machine, so maybe you can help debug it some more. Here are some steps:

1. Judging by the "overflow in correspondences" message, the segfault happens inside the correspondences function, not in the test. However, this is still probably a result of some bad allocation.

2. What's badly allocated, then, is something in the loop counters because it loops to overflow. What are the loop counter maximum values at the segfault time? Were they like that before the function was called or did they change? I'm talking about the num_targets array and possibly the .n fields that are used to loop over candidates.

3. The overflow message appears in each of the *_camera_matching functions. Do all the respective tests fail at one time or another, or just one of them, say the 4-camera? That would help localize the bug.

**Comment by alexlib** [comment]
only 4 cams test print overflow. 

now there's this one: 
```
15: check_correspondences(1083,0x7fffdf7313c0) malloc: *** error for object 0x7fc9c94035e8: incorrect checksum for freed object - object was probably modified after being freed.
15: *** set a breakpoint in malloc_error_break to debug
```

**Comment by alexlib** [comment]
only the ```test_correspondences()``` fails

**Comment by alexlib** [comment]
and it works perfectly if I compile and run it through XCode. it fails only when I run tests in the command line using ```make verify```

**Comment by alexlib** [comment]
suggest to close this issue until something more coherent will be identified

**Comment by alexlib** [comment]
new observation. the test fails the match_counts are now: 
```
3 
13 
0 
16
```

**Comment by alexlib** [comment]
so it fails 
- only with ```cmake -DCMAKE_BUILD_TYPE=Debug```

all other options: XCode compilated, cmake with a Release type, all pass.
I close this issue.

**Comment by yosefm** [comment]
If it fails in debug builds then there's a memory allocation problem. Maybe we won't find it now, but I think it's good to leave it open.
