### ISSUE TITLE
new failure with tests on Ubuntu 

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv#150]
10: Test command: /home/alex/openptv/liboptv/build/tests/check_imgcoord
10: Test timeout computed to be: 9.99988e+06
10: Running suite(s): Imgcoord
10: 60%: Checks: 5, Failures: 2, Errors: 0
10: /home/alex/openptv/liboptv/tests/check_imgcoord.c:155:F:Distorted image coordinates:test_distorted_centered_cam:0: Assertion 'x == 10./6.*(1 - 0.01*r*r)' failed
10: /home/alex/openptv/liboptv/tests/check_imgcoord.c:65:F:Shifted sensor not ignored:test_shifted_sensor:0: Assertion 'x == 2*(y - 0.1) + 0.1' failed
10/16 Test #10: check_imgcoord ...................***Failed    0.00 sec
test 11
      Start 11: check_sortgrid

**Comment by alexlib** [comment]
See the full test log
https://pastebin.com/VY8PmiLj

**Comment by yosefm** [comment]
When did it start failing? What changed?

**Comment by alexlib** [comment]
It appeared today on Ubuntu 14.04. Not clear what changed. maybe an upgrade to gcc with all the upgrades of Ubuntu.

**Comment by alexlib** [comment]
it doesn't appear on Mac OS X

**Comment by yosefm** [comment]
I've had a similar experience yesterday. Test check_multimed.c started failing, but not always, and after a while started passing which makes it hard to debug. I have done some investigating, haven't found an answer yet. But I think it can't be a buffer overflow, because efence should catch that. Maybe a better candidate is reading uninitialized memory somewhere. Probably in the parameters or calibration reading code, which multimed and imgcoord should share.

**Comment by alexlib** [comment]
maybe it's all the same ? Now I do not have failures on Ubuntu anymore - see #152
